--Much Better Option than IDENTITY and GUIDS 

BEGIN TRANSACTION
CREATE SEQUENCE sq1 AS INT
START WITH 1
INCREMENT BY 1
MAXVALUE 9999
CYCLE

--OR--
CREATE SEQUENCE sq2 as INT

select * from sys.sequences

--TO GET THE VALUE OF SEQUENCE--

select NEXT VALUE for sq1 AS NEXTVAUE  --IT WILL ALWAYS GENERATE THE VALUE 1 UNLIKE the IDENTITY 

ROLLBACK TRANSACTION




